<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [5]:
#You can define a named function as such:

def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
    
#To use/call the function,:
greeting("Super Man")

#or

greeting(name="Super Man")

#the function's name is greeting and it accepts a single argument called name
#the colon (:) and indentation demarcates the function's code block
# the keyword return get an output from the function


'Hello Super Man!'

In [2]:
#Can assign the returned value of a function to a variable as uch:
greet=greeting(name='Super Man')
print(greet)

Hello Super Man!


In [4]:
#A function can return most anything
#Below is an example of a function that accepts a list and returns the maximum, minimum and mean
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

#To use it:
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

### 1.2 Named functions that don’t return

A function does **not** have to return anything. For e.g., print() does something but does not return a value. Such functions are needed for things such as saving data to a file.


### 1.3 Anonymous functions

In [5]:
#Anonymous functions (also known as lambda functions) are short one-liners
#The following examples accepts a single argument called name.

my_short_function = lambda name: f"Hello {name}!"

#Can use it as such:
my_short_function(name="Super Man")

#A lambda function always returns the value of the last statement
#Above example not a very good anonymous because a name is used

'Hello Super Man!'

In [7]:
#An example where things get really anonymous:
#Say I want ot sort a 2D list, the sorted() function can be used as follow:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element)
    
#This sorting is based on comparing the first elements of the sub-lists
#If I want to use some other criteria, need to specify a key that can be used for comparison
#A lambda function can be used for this as follows:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element
    
#This is powerful as I can specify almost any criterion I like. For example, can sort according to the sum of the elements of the sub-lists:
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [8]:
#In python, arguments to our function can be optional
#To do this, we need to give the argument a default value:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
#Running this function without an argument now will not throw an error
greeting()


'Hello no one!'

In [6]:
#Looking at the documentation for print(),

#Docstring:
#    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
#
#    Prints the values to a stream, or to sys.stdout by default.
#    Optional keyword arguments:
#    file:  a file-like object (stream); defaults to the current sys.stdout.
#    sep:   string inserted between values, default a space.
#    end:   string appended after the last value, default a newline.
#    flush: whether to forcibly flush the stream.
#    Type:      builtin_function_or_method

#print() can accept other arguments and are optional with default values
#However, we can specify them if we like:
print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

1. **Abstraction of details**: The most important benefit of functions is the ability to strategise. Breaking up complicated solution into modular chunks allows one to think about it more easily. Easier to focus on overall solution because there are no unnecessarty information. This hiding of 'stuff' is called abstraction
2. **Reusability of code**: Easily reuse a function instead of copying and pasting at different places
3. **Maintainability of code**: Easier to change and maintain because you only need to make changes in one place, at the function definition

### 2.2 A word of caution

- Functions can be abused by trying to do too much or having too many functions. 
- They can also be overused
- Having too many functions makes it difficult to read your code and increases computational overheads


## Exercise 1 :  Do you know why?

Even though there is no else statement, as long as name != 'Batman', the greeting function will not return 'Hello Batman! So, nice to meet you!'. The function will continue to move on to the next line of code and return f'Hello {name}!'




## Exercise 2 :  Calculator functions

In [8]:
y=np.array([64, 0, 56, 24, 73])
y == 0

np.any(y)

True

In [12]:
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if np.any(y == 0):
        exit()
    else:
        return x / y
    
x = np.array([36, 34, 44, 76, 27])
y = np.array([64, 66, 56, 24, 73])

print(add(x, y))
print(subtract(x, y))
print(multiply(x, y))
print(divide(x, y))

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 3 :  max_info() with NumPy

In [13]:
def max_info(numbers):
    return np.max(numbers), np.argmax(numbers)

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

max_info(numbers)

(83, 2)