<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [ ]:
import numpy as np
# Your code here
#Python Lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

#Numpy Arrays
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

#Dictionary
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

#Dictionaries use a key and an associated value separated by a :


### 1.2 Accessing data from a list (or array)

In [1]:

# Your code here
#Python is a zero-indexed language, so it starts counting at 0
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_real_names[0])
print(py_super_names[0])

#using a negative index allows us to count from the back of the list. Using index -1 will give the last element
print(py_super_names[2])    # Forward indexing 
                            # We need to know the size 
                            # beforehand for this to work.
        
print(py_super_names[-1])   # Reverse indexing

Natasha Romanoff
Black Widow
Doctor Strange
Doctor Strange


### 1.3 Accessing data from a dictionary

In [3]:

# Your code here
#Dictionaries hold data (values) paired with a key. i.e. you can access the value using key
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
print(superhero_info["Natasha Romanoff"])

#Can access all the keys and values as follows:
superhero_info.keys()
superhero_info.values()

Black Widow


dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [4]:

# 2D list (or array)
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]


## 2 Lists vs. Arrays

### 2.1 Size

In [8]:

#Use the len() function to know how many elements there are in lists
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

len(py_list_2d)
len(np_array_2d)

np_array_2d.shape 
#absence of brackets () in shape above. This is because shape is not a function. Instead, it is a property of attribute of the NumPy array

(10, 2)

### 2.2 Arrays are fussy about type

In [9]:

#One prominent difference between lists and arrays is that arrays like having a single data type; lists are more accommodating
py_list = [1, 1.5, 'A']
np.array(py_list)
#numbers are converted to Englist with ''

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [11]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
py_list + 10        # Won't work!
np_array + 10       # Works



array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [12]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

# Adding python list adds elements to the list
py_list_1 + py_list_2

#Adding numpy arrays performs arithmetic additions to the elements
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [13]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

# Similar to addition, multiplying by a number makes a list grow
py_list*2

#whereas an array multiples its elements by the number
np_array*2


array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

#Squaring a list won't work
py_list**2                      # Won't work!  

#Squaring an array squares the elements
np_array**2

### 2.7 Asking questions

In [14]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list == 3     # Works, but what IS the question?
py_list > 3      # Won't work!

#Compares the elements in the array
np_array == 3  
np_array > 3  


TypeError: '>' not supported between instances of 'list' and 'int'

### 2.8 Mathematics

In [16]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
py_list.sum()   # Won't work!
np_array.sum()
np_array.mean()
np_array.max()
np_array.min()

AttributeError: 'list' object has no attribute 'sum'

## Exercise 1 :  Total recall?

1. One similarity between list and array is that they both contain elements. Another similarity between list and array is the you can access the elements using index

2. One difference between list and array is that operations on a list usually works on the whole list while operations on an array usually works on the individual elements of the array. Another difference between list and array is that more than one data type can be in a list but not for an array.

3. A dictionary stores data using a key value format




## Exercise 2 :  Index me

In [18]:



# Your solution here
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'



a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [20]:



# Your solution here
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [25]:



# Your solution here
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]

np_numbers = np.array(numbers)

number_of_1s = sum(np_numbers == 1)
print(number_of_1s)

9
